# Generated by Django 3.0.7 on 2020-07-25 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='username',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='network.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.CharField(default='', max_length=150)),
                ('user', models.ManyToManyField(blank=True, related_name='user_following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
